#ifndef _OLED_COMMANDS_H_
#define _OLED_COMMANDS_H_

#define OLED_CHARGE_PUMP		0x8D
#define OLED_COLUMN_ADDR		0x21
#define OLED_COM_SCAN_DEC		0xC8
#define OLED_COM_SCAN_INC		0xC0
#define OLED_DISP_OFF			0xAE
#define OLED_DISP_ON			0xAF
#define OLED_DISP_ALL_ON		0xA5
#define OLED_DISP_ALL_ON_RESUME	0xA4
#define OLED_DISP_INVERT		0xA7
#define OLED_DISP_NORMAL		0xA6
#define OLED_MEMORY_MODE		0x20
#define OLED_PAGE_ADDR			0x22
#define OLED_SEG_REMAP			0xA0
#define OLED_SET_VCOM_DETECT	0xDB
#define OLED_SET_COM_PINS		0xDA
#define OLED_SET_CONTRAST		0x81
#define OLED_SET_DISP_CLOCK_DIV 0xD5
#define OLED_SET_DISP_OFFSET	0xD3
#define OLED_SET_HIGH_COLUMN	0x10
#define OLED_SET_LOW_COLUMN		0x00
#define OLED_SET_MULTIPLEX		0xA8
#define OLED_SET_PRECHARGE		0xD9
#define OLED_SET_START_LINE		0x40
#define OLED_VCC_EXTERNAL		0x01
#define OLED_VCC_SWITCHCAP		0x02

// Scrolling
#define OLED_SCROLL_ACTIVATE	0x2F
#define OLED_SCROLL_DEACTIVATE	0x2E
#define OLED_SCROLL_SET_AREA_V	0xA3
#define OLED_SCROLL_RH			0x26
#define OLED_SCROLL_LH			0x27
#define OLED_SCROLL_V_AND_RH	0x29
#define OLED_SCROLL_V_AND_LH	0x2A

#endif // !_OLED_COMMANDS_H_
